baseURL = "https://Next-Start.github.io/"
languageCode = "en-us"
title = "Next Start"
theme = "navigator-hugo"



summaryLength = 10

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = "" # your analitics ID

enableGitInfo = false
pygmentsCodeFences = true

# Multilangues setup
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir = true
DefaultContentLanguage = "en"

# Site Params
[params]
logo = "images/logo.png"

# meta data
author = "Angus-C"
description = "Created for CTF challenge"


############# 2 - Site en ENGLISH
[Languages.en]
weight = 2
languageCode = "en-us"
title = "Next Start"
dateFormat = "January 2, 2006"
home = "EN Home"
logo = "images/logo.png"
menufixed = false

footerDescription = "Integer posuere erat a ante venenati dapibus posuere velit aliquet. Fusce dapibus, tellus cursus commodo, tortor mauris sed posuere."
footerServiceTitle = "Service"
footerQuicklinkTitle = "Quicklinks"
footerAboutTitle = "About"
footerSubscribeTitle = "Subscribe"


# cookies
[params.cookies]
enable = true
expire_days = 2

# Hero Area Section
[Languages.en.params.hero]
enable  = true
heading = "We love to help startups grow"
description = "We are incredibly passionate about startups and have been helping startups reach their full potential for 10 years! We'd love to be apart of your startups journey too."
button  = false
btnText = "Know More"
btnURL  = "https://themefisher.com/"
videoThumb = "images/slider/video-player-thumb.jpg"
videoURL   = "https://www.youtube.com/watch?v=Z-iPp6yn0hw&ab_channel=mortrek"

# About 2 Section
[Languages.en.params.aboutSm]
enable  = true
title   = "As a startup ourselves we have great experience in the area"
description = "Ten years ago NextStart launched as a startup with the humble mission of making other startups work! This gives us the unique perspective of starting where you started and the experience needed to make your startup a success."

# Blog Section On Homepage
#[Languages.en.params.blog]
#enable  = true
#topTitle= "OUR STORY"
#title   = "Blog."
#subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"

# Contact Section
#[Languages.en.params.contact]
#enable  = true
#topTitle= "DROP US A NOTE"
#title   = "Contact Us."
#subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"
#address = "14/05, Stockhome <br> Victori Palace , United States"
#phone   = "(03) 9283 2617"
#fax     = "+61 3827 3590"
#facebook= "https://www.facebook.com/"
#twitter = "https://twitter.com/"
#linkedin= "https://www.linkedin.com/"
#dribbble= "https://dribbble.com/"
#instagram= "https://www.instagram.com/"
#mapLatitude = "51.507351"
#mapLongitude= "-0.127758"
#mapMarker   = "images/marker.png"

# Call to Action Section on About Page
[Languages.en.params.cta]
enable  = true
bg      = "images/call-to-action/call-to-action-bg-2.jpg"
title   = "Let's Build A Startup Together"
subtitle= "Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin bibendum auctor, <br> nisi elit consequat ipsum, nesagittis sem nid elit. Duis sed odio sitain elit."
btnText = "Contact Us"

# We Used Themefisher Icon font for Icon, for more details check this github repository - https://github.com/themefisher/themefisher-font

# Site Menus
[menu]
# Navbar Menus
[[menu.nav]]
name    = "about"
url     = "about"
weight  = 2
[[menu.nav]]
name    = "service"
url     = "service"
weight  = 3
[[menu.nav]]
name    = "portfolio"
url     = "portfolio"
weight  = 4
[[menu.nav]]
name    = "blog"
url     = "blog"
weight  = 5
[[menu.nav]]
name    = "contact"
url     = "contact"
weight  = 6

# Footer Service Menu
[[menu.service]]
name    = "graphicdesign"
url     = "service"
weight  = 1
[[menu.service]]
name    = "webdesign"
url     = "service"
weight  = 2
[[menu.service]]
name    = "webdevelopment"
url     = "service"
weight  = 3

# Footer Quick links Menu
[[menu.quicklink]]
name    = "partners"
url     = "about"
weight  = 1
[[menu.quicklink]]
name    = "about"
url     = "about"
weight  = 2
[[menu.quicklink]]
name    = "faqs"
url     = "about"
weight  = 3
[[menu.quicklink]]
name    = "badges"
url     = "about"
weight  = 4